name: Docker Workflow

on:
  push:
    paths:
      - "**.java"
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Clean
        run: mvn clean
      - name: Build
        run: mvn compile
      - name: Short tests
        run: mvn test -Dtest=CalculatorTest
      - name: Long tests
        run: mvn test -Dtest=CalculatorTestThorough
